[2022-11-21T21:12:52.190-0300] {processor.py:153} INFO - Started process (PID=3014) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:12:52.191-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:12:52.191-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:12:52.191-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:12:52.197-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:12:52.192-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:12:52.197-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:12:52.228-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.044 seconds
[2022-11-21T21:13:31.916-0300] {processor.py:153} INFO - Started process (PID=3119) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:13:31.919-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:13:31.920-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:13:31.920-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:13:31.924-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:13:31.922-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:13:31.925-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:13:31.953-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.046 seconds
[2022-11-21T21:14:03.208-0300] {processor.py:153} INFO - Started process (PID=3259) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:14:03.213-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:14:03.214-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:14:03.214-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:14:03.223-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:14:03.221-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:14:03.223-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:14:03.272-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.068 seconds
[2022-11-21T21:14:37.496-0300] {processor.py:153} INFO - Started process (PID=3449) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:14:37.502-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:14:37.502-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:14:37.502-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:14:37.535-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:14:37.527-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:14:37.535-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:14:37.887-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.402 seconds
[2022-11-21T21:15:47.240-0300] {processor.py:153} INFO - Started process (PID=3507) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:15:47.245-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:15:47.246-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:15:47.245-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:15:47.274-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:15:47.267-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:15:47.274-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:15:47.375-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.147 seconds
[2022-11-21T21:16:58.854-0300] {processor.py:153} INFO - Started process (PID=3540) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:16:58.859-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:16:58.860-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:16:58.860-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:16:58.894-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:16:58.885-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:16:58.895-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:16:59.531-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.689 seconds
[2022-11-21T21:38:12.934-0300] {processor.py:153} INFO - Started process (PID=7748) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:38:12.936-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:38:12.936-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:38:12.936-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:38:12.943-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:38:12.938-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:38:12.943-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:38:13.231-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.299 seconds
[2022-11-21T21:38:52.639-0300] {processor.py:153} INFO - Started process (PID=8064) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:38:52.641-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:38:52.641-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:38:52.641-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:38:52.651-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:38:52.646-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:38:52.651-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:38:52.685-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.051 seconds
[2022-11-21T21:39:26.792-0300] {processor.py:153} INFO - Started process (PID=8097) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:39:26.798-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:39:26.799-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:39:26.799-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:39:26.802-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:39:26.801-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:39:26.802-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:39:26.827-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.039 seconds
[2022-11-21T21:39:58.865-0300] {processor.py:153} INFO - Started process (PID=8164) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:39:58.866-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:39:58.867-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:39:58.867-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:39:58.871-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:39:58.869-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:39:58.871-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:39:58.901-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.043 seconds
[2022-11-21T21:40:30.306-0300] {processor.py:153} INFO - Started process (PID=8500) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:40:30.314-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:40:30.315-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:40:30.315-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:40:30.321-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:40:30.320-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:40:30.322-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:40:30.389-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.090 seconds
[2022-11-21T21:41:04.124-0300] {processor.py:153} INFO - Started process (PID=8708) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:41:04.131-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:41:04.132-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:41:04.132-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:41:04.140-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:41:04.138-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:41:04.141-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:41:04.171-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.055 seconds
[2022-11-21T21:41:35.914-0300] {processor.py:153} INFO - Started process (PID=8895) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:41:35.915-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:41:35.916-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:41:35.916-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:41:35.920-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:41:35.918-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:41:35.920-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:41:35.945-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.036 seconds
[2022-11-21T21:42:06.326-0300] {processor.py:153} INFO - Started process (PID=9079) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:42:06.327-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:42:06.329-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:42:06.328-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:42:06.333-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:42:06.331-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:42:06.333-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:42:06.366-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.045 seconds
[2022-11-21T21:42:38.612-0300] {processor.py:153} INFO - Started process (PID=9261) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:42:38.614-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:42:38.615-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:42:38.615-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:42:38.618-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:42:38.617-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:42:38.618-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:42:38.652-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.044 seconds
[2022-11-21T21:43:10.917-0300] {processor.py:153} INFO - Started process (PID=9469) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:43:10.919-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:43:10.920-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:43:10.920-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:43:10.922-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:43:10.921-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:43:10.923-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:43:10.966-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.055 seconds
[2022-11-21T21:43:43.239-0300] {processor.py:153} INFO - Started process (PID=9651) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:43:43.243-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:43:43.244-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:43:43.244-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:43:43.254-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:43:43.245-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:43:43.254-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:43:43.314-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.084 seconds
[2022-11-21T21:44:15.586-0300] {processor.py:153} INFO - Started process (PID=9692) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:44:15.587-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:44:15.587-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:44:15.587-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:44:15.590-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:44:15.589-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:44:15.590-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:44:15.616-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.033 seconds
[2022-11-21T21:44:46.123-0300] {processor.py:153} INFO - Started process (PID=9732) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:44:46.129-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:44:46.130-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:44:46.130-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:44:46.136-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:44:46.134-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:44:46.137-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:44:46.164-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.045 seconds
[2022-11-21T21:45:21.663-0300] {processor.py:153} INFO - Started process (PID=9774) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:45:21.664-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:45:21.665-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:45:21.665-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:45:21.669-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:45:21.668-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:45:21.670-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:45:21.741-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.084 seconds
[2022-11-21T21:45:52.246-0300] {processor.py:153} INFO - Started process (PID=9836) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:45:52.247-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:45:52.248-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:45:52.248-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:45:52.251-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:45:52.250-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:45:52.251-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:45:52.287-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.046 seconds
[2022-11-21T21:46:23.422-0300] {processor.py:153} INFO - Started process (PID=10025) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:46:23.424-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:46:23.425-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:46:23.425-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:46:23.429-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:46:23.428-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:46:23.429-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:46:23.458-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.041 seconds
[2022-11-21T21:46:58.838-0300] {processor.py:153} INFO - Started process (PID=10243) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:46:58.840-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:46:58.841-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:46:58.840-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:46:58.850-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:46:58.845-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:46:58.850-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:46:58.878-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.045 seconds
[2022-11-21T21:47:35.506-0300] {processor.py:153} INFO - Started process (PID=10453) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:47:35.507-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:47:35.508-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:47:35.508-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:47:35.511-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:47:35.510-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:47:35.512-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:47:35.548-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.046 seconds
[2022-11-21T21:48:06.783-0300] {processor.py:153} INFO - Started process (PID=10587) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:48:06.784-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:48:06.785-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:48:06.784-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:48:06.787-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:48:06.786-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:48:06.787-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:48:06.970-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.190 seconds
[2022-11-21T21:48:41.972-0300] {processor.py:153} INFO - Started process (PID=10728) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:48:41.983-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:48:41.984-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:48:41.983-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:48:41.986-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:48:41.985-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:48:41.987-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:48:42.015-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.048 seconds
[2022-11-21T21:49:12.585-0300] {processor.py:153} INFO - Started process (PID=10761) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:49:12.587-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:49:12.588-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:49:12.587-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:49:12.591-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:49:12.590-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:49:12.592-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:49:12.617-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.038 seconds
[2022-11-21T21:49:46.819-0300] {processor.py:153} INFO - Started process (PID=10796) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:49:46.821-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:49:46.822-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:49:46.821-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:49:46.825-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:49:46.824-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:49:46.826-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:49:46.895-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.081 seconds
[2022-11-21T21:50:22.478-0300] {processor.py:153} INFO - Started process (PID=10843) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:50:22.479-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:50:22.480-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:50:22.480-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:50:22.483-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:50:22.482-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:50:22.484-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:50:22.516-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.042 seconds
[2022-11-21T21:50:54.874-0300] {processor.py:153} INFO - Started process (PID=10889) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:50:54.876-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:50:54.877-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:50:54.876-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:50:54.882-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:50:54.880-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:50:54.882-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:50:54.907-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.039 seconds
[2022-11-21T21:51:28.700-0300] {processor.py:153} INFO - Started process (PID=10924) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:51:28.702-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:51:28.703-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:51:28.703-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:51:28.706-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:51:28.705-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:51:28.707-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:51:28.745-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.050 seconds
[2022-11-21T21:52:00.437-0300] {processor.py:153} INFO - Started process (PID=10954) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:52:00.438-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:52:00.439-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:52:00.439-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:52:00.442-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:52:00.441-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:52:00.443-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:52:00.481-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.057 seconds
[2022-11-21T21:52:35.377-0300] {processor.py:153} INFO - Started process (PID=10989) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:52:35.384-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:52:35.385-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:52:35.384-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:52:35.388-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:52:35.386-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:52:35.388-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:52:35.412-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.038 seconds
[2022-11-21T21:53:09.359-0300] {processor.py:153} INFO - Started process (PID=11039) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:53:09.361-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:53:09.362-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:53:09.361-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:53:09.365-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:53:09.364-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:53:09.365-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:53:09.398-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.044 seconds
[2022-11-21T21:53:42.060-0300] {processor.py:153} INFO - Started process (PID=11225) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:53:42.062-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:53:42.063-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:53:42.063-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:53:42.067-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:53:42.066-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-21T21:53:42.068-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:53:42.098-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.044 seconds
[2022-11-21T21:54:16.100-0300] {processor.py:153} INFO - Started process (PID=11440) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:54:16.101-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:54:16.102-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:54:16.102-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:54:16.110-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:54:16.108-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators import TwitterOperator
ImportError: cannot import name 'TwitterOperator' from 'airflow.operators' (/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2022-11-21T21:54:16.110-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:54:16.136-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.042 seconds
[2022-11-21T21:54:49.631-0300] {processor.py:153} INFO - Started process (PID=11549) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:54:49.633-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:54:49.633-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:54:49.633-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:54:49.637-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:54:49.636-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators import TwitterOperator
ImportError: cannot import name 'TwitterOperator' from 'airflow.operators' (/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2022-11-21T21:54:49.637-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:54:49.661-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.035 seconds
[2022-11-21T21:55:19.983-0300] {processor.py:153} INFO - Started process (PID=11575) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:55:19.985-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:55:19.985-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:55:19.985-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:55:19.988-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:55:19.987-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators import TwitterOperator
ImportError: cannot import name 'TwitterOperator' from 'airflow.operators' (/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2022-11-21T21:55:19.988-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:55:20.007-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.026 seconds
[2022-11-21T21:55:58.768-0300] {processor.py:153} INFO - Started process (PID=11940) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:55:58.773-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:55:58.773-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:55:58.773-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:55:58.787-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:55:58.783-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators import TwitterOperator
ImportError: cannot import name 'TwitterOperator' from 'airflow.operators' (/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2022-11-21T21:55:58.787-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:55:58.861-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.100 seconds
[2022-11-21T21:57:32.455-0300] {processor.py:153} INFO - Started process (PID=12087) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:57:32.691-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T21:57:33.604-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:57:33.446-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:57:34.800-0300] {logging_mixin.py:115} INFO - [2022-11-21T21:57:34.214-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators import TwitterOperator
ImportError: cannot import name 'TwitterOperator' from 'airflow.operators' (/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2022-11-21T21:57:35.399-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T21:57:58.960-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 26.545 seconds
[2022-11-21T22:03:28.754-0300] {processor.py:153} INFO - Started process (PID=2194) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:03:28.763-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:03:28.764-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:03:28.764-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:03:28.768-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:03:28.765-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators import TwitterOperator
ImportError: cannot import name 'TwitterOperator' from 'airflow.operators' (/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2022-11-21T22:03:28.768-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:03:28.791-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.040 seconds
[2022-11-21T22:04:09.036-0300] {processor.py:153} INFO - Started process (PID=2500) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:04:09.042-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:04:09.043-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:04:09.043-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:04:09.049-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:04:09.046-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators import TwitterOperator
ImportError: cannot import name 'TwitterOperator' from 'airflow.operators' (/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2022-11-21T22:04:09.051-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:04:09.085-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.052 seconds
[2022-11-21T22:04:40.772-0300] {processor.py:153} INFO - Started process (PID=2540) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:04:40.775-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:04:40.776-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:04:40.776-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:04:40.778-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:04:40.777-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators import TwitterOperator
ImportError: cannot import name 'TwitterOperator' from 'airflow.operators' (/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2022-11-21T22:04:40.783-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:04:40.819-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.050 seconds
[2022-11-21T22:05:15.162-0300] {processor.py:153} INFO - Started process (PID=2893) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:05:15.168-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:05:15.169-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:05:15.169-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:05:15.176-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:05:15.172-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators import TwitterOperator
ImportError: cannot import name 'TwitterOperator' from 'airflow.operators' (/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2022-11-21T22:05:15.176-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:05:15.239-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.080 seconds
[2022-11-21T22:05:45.581-0300] {processor.py:153} INFO - Started process (PID=3245) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:05:45.583-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:05:45.583-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:05:45.583-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:05:45.588-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:05:45.586-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators import TwitterOperator
ImportError: cannot import name 'TwitterOperator' from 'airflow.operators' (/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2022-11-21T22:05:45.589-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:05:45.613-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.035 seconds
[2022-11-21T22:06:18.481-0300] {processor.py:153} INFO - Started process (PID=3616) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:06:18.484-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:06:18.484-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:06:18.484-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:06:18.497-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:06:18.491-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators import TwitterOperator
ImportError: cannot import name 'TwitterOperator' from 'airflow.operators' (/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2022-11-21T22:06:18.497-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:06:18.528-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.055 seconds
[2022-11-21T22:06:51.750-0300] {processor.py:153} INFO - Started process (PID=3834) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:06:51.753-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:06:51.754-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:06:51.753-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:06:51.761-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:06:51.756-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators import TwitterOperator
ImportError: cannot import name 'TwitterOperator' from 'airflow.operators' (/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2022-11-21T22:06:51.762-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:06:51.818-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.080 seconds
[2022-11-21T22:07:25.851-0300] {processor.py:153} INFO - Started process (PID=4018) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:07:25.857-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:07:25.860-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:07:25.859-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:07:25.882-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:07:25.874-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators import TwitterOperator
ImportError: cannot import name 'TwitterOperator' from 'airflow.operators' (/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2022-11-21T22:07:25.884-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:07:25.988-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.156 seconds
[2022-11-21T22:07:58.051-0300] {processor.py:153} INFO - Started process (PID=4201) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:07:58.053-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:07:58.054-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:07:58.053-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:07:58.056-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:07:58.055-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators import TwitterOperator
ImportError: cannot import name 'TwitterOperator' from 'airflow.operators' (/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2022-11-21T22:07:58.059-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:07:58.092-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.052 seconds
[2022-11-21T22:08:32.049-0300] {processor.py:153} INFO - Started process (PID=4409) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:08:32.051-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:08:32.052-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:08:32.051-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:08:32.056-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:08:32.054-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 5, in <module>
    from twitter_operator import TwitterOperator
ModuleNotFoundError: No module named 'twitter_operator'
[2022-11-21T22:08:32.057-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:08:32.092-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.049 seconds
[2022-11-21T22:09:03.402-0300] {processor.py:153} INFO - Started process (PID=4626) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:09:03.410-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:09:03.411-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:09:03.411-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:09:03.416-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:09:03.414-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 5, in <module>
    from twitter_operator import TwitterOperator
ModuleNotFoundError: No module named 'twitter_operator'
[2022-11-21T22:09:03.416-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:09:03.446-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.049 seconds
[2022-11-21T22:09:33.808-0300] {processor.py:153} INFO - Started process (PID=5004) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:09:33.813-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:09:33.814-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:09:33.813-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:09:33.819-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:09:33.817-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 5, in <module>
    from twitter_operator import TwitterOperator
ModuleNotFoundError: No module named 'twitter_operator'
[2022-11-21T22:09:33.820-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:09:33.863-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.058 seconds
[2022-11-21T22:10:08.302-0300] {processor.py:153} INFO - Started process (PID=5038) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:10:08.303-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:10:08.305-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:10:08.304-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:10:08.309-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:10:08.307-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 5, in <module>
    from twitter_operator import TwitterOperator
ModuleNotFoundError: No module named 'twitter_operator'
[2022-11-21T22:10:08.309-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:10:08.339-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.042 seconds
[2022-11-21T22:10:40.364-0300] {processor.py:153} INFO - Started process (PID=5327) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:10:40.369-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:10:40.370-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:10:40.369-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:10:40.377-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:10:40.373-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 5, in <module>
    from twitter_operator import TwitterOperator
ModuleNotFoundError: No module named 'twitter_operator'
[2022-11-21T22:10:40.378-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:10:40.426-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.065 seconds
[2022-11-21T22:11:16.970-0300] {processor.py:153} INFO - Started process (PID=5556) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:11:16.971-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:11:16.973-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:11:16.972-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:11:16.983-0300] {processor.py:650} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:11:17.061-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:11:17.061-0300] {manager.py:508} INFO - Created Permission View: can delete on DAG:twitter_dag
[2022-11-21T22:11:17.075-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:11:17.075-0300] {manager.py:508} INFO - Created Permission View: can edit on DAG:twitter_dag
[2022-11-21T22:11:17.098-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:11:17.098-0300] {manager.py:508} INFO - Created Permission View: can read on DAG:twitter_dag
[2022-11-21T22:11:17.099-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:11:17.098-0300] {dag.py:2429} INFO - Sync 1 DAGs
[2022-11-21T22:11:17.111-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:11:17.111-0300] {dag.py:2448} INFO - Creating ORM DAG for twitter_dag
[2022-11-21T22:11:17.124-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:11:17.124-0300] {dag.py:2977} INFO - Setting next_dagrun for twitter_dag to 2022-11-21T22:11:16.981146+00:00, run_after=2022-11-22T22:11:16.981146+00:00
[2022-11-21T22:11:17.148-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.183 seconds
[2022-11-21T22:11:51.635-0300] {processor.py:153} INFO - Started process (PID=5922) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:11:51.638-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:11:51.638-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:11:51.638-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:11:51.653-0300] {processor.py:650} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:11:51.759-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:11:51.759-0300] {dag.py:2429} INFO - Sync 1 DAGs
[2022-11-21T22:11:51.789-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:11:51.789-0300] {dag.py:2977} INFO - Setting next_dagrun for twitter_dag to 2022-11-21T22:11:51.650678+00:00, run_after=2022-11-22T22:11:51.650678+00:00
[2022-11-21T22:11:51.817-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.185 seconds
[2022-11-21T22:12:25.770-0300] {processor.py:153} INFO - Started process (PID=5956) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:12:25.772-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:12:25.773-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:12:25.773-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:12:25.784-0300] {processor.py:650} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:12:25.855-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:12:25.854-0300] {dag.py:2429} INFO - Sync 1 DAGs
[2022-11-21T22:12:25.868-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:12:25.868-0300] {dag.py:2977} INFO - Setting next_dagrun for twitter_dag to 2022-11-21T22:12:25.782328+00:00, run_after=2022-11-22T22:12:25.782328+00:00
[2022-11-21T22:12:25.939-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.173 seconds
[2022-11-21T22:12:58.878-0300] {processor.py:153} INFO - Started process (PID=6001) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:12:58.880-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:12:58.881-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:12:58.881-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:12:58.891-0300] {processor.py:650} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:12:58.934-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:12:58.934-0300] {dag.py:2429} INFO - Sync 1 DAGs
[2022-11-21T22:12:58.949-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:12:58.948-0300] {dag.py:2977} INFO - Setting next_dagrun for twitter_dag to 2022-11-21T22:12:58.889160+00:00, run_after=2022-11-22T22:12:58.889160+00:00
[2022-11-21T22:12:58.969-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.096 seconds
[2022-11-21T22:13:35.502-0300] {processor.py:153} INFO - Started process (PID=6037) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:13:35.503-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:13:35.503-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:13:35.503-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:13:35.512-0300] {processor.py:650} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:13:35.555-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:13:35.555-0300] {dag.py:2429} INFO - Sync 1 DAGs
[2022-11-21T22:13:35.568-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:13:35.567-0300] {dag.py:2977} INFO - Setting next_dagrun for twitter_dag to 2022-11-21T22:13:35.510254+00:00, run_after=2022-11-22T22:13:35.510254+00:00
[2022-11-21T22:13:35.589-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.092 seconds
[2022-11-21T22:14:09.648-0300] {processor.py:153} INFO - Started process (PID=6072) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:14:09.649-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:14:09.651-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:14:09.650-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:14:09.662-0300] {processor.py:650} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:14:09.707-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:14:09.707-0300] {dag.py:2429} INFO - Sync 1 DAGs
[2022-11-21T22:14:09.720-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:14:09.720-0300] {dag.py:2977} INFO - Setting next_dagrun for twitter_dag to 2022-11-21T22:14:09.659955+00:00, run_after=2022-11-22T22:14:09.659955+00:00
[2022-11-21T22:14:09.740-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.098 seconds
[2022-11-21T22:14:41.926-0300] {processor.py:153} INFO - Started process (PID=6105) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:14:41.928-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:14:41.929-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:14:41.929-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:14:41.941-0300] {processor.py:650} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:14:41.982-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:14:41.982-0300] {dag.py:2429} INFO - Sync 1 DAGs
[2022-11-21T22:14:41.994-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:14:41.994-0300] {dag.py:2977} INFO - Setting next_dagrun for twitter_dag to 2022-11-21T22:14:41.938274+00:00, run_after=2022-11-22T22:14:41.938274+00:00
[2022-11-21T22:14:42.077-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.156 seconds
[2022-11-21T22:15:12.743-0300] {processor.py:153} INFO - Started process (PID=6135) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:15:12.745-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:15:12.746-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:15:12.746-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:15:12.759-0300] {processor.py:650} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:15:12.801-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:15:12.801-0300] {dag.py:2429} INFO - Sync 1 DAGs
[2022-11-21T22:15:12.813-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:15:12.813-0300] {dag.py:2977} INFO - Setting next_dagrun for twitter_dag to 2022-11-21T22:15:12.756139+00:00, run_after=2022-11-22T22:15:12.756139+00:00
[2022-11-21T22:15:12.835-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.098 seconds
[2022-11-21T22:15:44.372-0300] {processor.py:153} INFO - Started process (PID=6167) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:15:44.373-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:15:44.375-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:15:44.374-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:15:44.386-0300] {processor.py:650} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:15:44.431-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:15:44.431-0300] {dag.py:2429} INFO - Sync 1 DAGs
[2022-11-21T22:15:44.452-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:15:44.452-0300] {dag.py:2977} INFO - Setting next_dagrun for twitter_dag to 2022-11-21T22:15:44.383773+00:00, run_after=2022-11-22T22:15:44.383773+00:00
[2022-11-21T22:15:44.470-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.104 seconds
[2022-11-21T22:16:15.481-0300] {processor.py:153} INFO - Started process (PID=6198) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:16:15.482-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:16:15.488-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:16:15.483-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:16:15.505-0300] {processor.py:650} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:16:15.562-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:16:15.561-0300] {dag.py:2429} INFO - Sync 1 DAGs
[2022-11-21T22:16:15.576-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:16:15.576-0300] {dag.py:2977} INFO - Setting next_dagrun for twitter_dag to 2022-11-21T22:16:15.499199+00:00, run_after=2022-11-22T22:16:15.499199+00:00
[2022-11-21T22:16:15.597-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.120 seconds
[2022-11-21T22:16:50.350-0300] {processor.py:153} INFO - Started process (PID=6248) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:16:50.352-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-21T22:16:50.353-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:16:50.353-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:16:50.364-0300] {processor.py:650} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-21T22:16:50.414-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:16:50.413-0300] {dag.py:2429} INFO - Sync 1 DAGs
[2022-11-21T22:16:50.430-0300] {logging_mixin.py:115} INFO - [2022-11-21T22:16:50.430-0300] {dag.py:2977} INFO - Setting next_dagrun for twitter_dag to 2022-11-21T22:16:50.361765+00:00, run_after=2022-11-22T22:16:50.361765+00:00
[2022-11-21T22:16:50.507-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.163 seconds
