[2022-11-18T16:09:29.759-0300] {processor.py:153} INFO - Started process (PID=4536) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:09:29.762-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-18T16:09:29.763-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:09:29.763-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:09:29.771-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:09:29.768-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 2, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-18T16:09:29.771-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:09:29.823-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.067 seconds
[2022-11-18T16:29:17.860-0300] {processor.py:153} INFO - Started process (PID=4714) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:29:17.964-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-18T16:29:17.970-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:29:17.965-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:29:19.062-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:29:18.663-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 2, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-18T16:29:19.131-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:29:20.798-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 2.977 seconds
[2022-11-18T16:39:45.924-0300] {processor.py:153} INFO - Started process (PID=4945) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:39:45.930-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-18T16:39:45.931-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:39:45.931-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:39:46.000-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:39:45.985-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 2, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-18T16:39:46.001-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:39:47.317-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 1.432 seconds
[2022-11-18T16:56:38.155-0300] {processor.py:153} INFO - Started process (PID=2184) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:56:38.156-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-18T16:56:38.157-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:56:38.157-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:56:38.160-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:56:38.158-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 2, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-18T16:56:38.161-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:56:38.321-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.168 seconds
[2022-11-18T16:57:16.538-0300] {processor.py:153} INFO - Started process (PID=2308) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:57:16.549-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-18T16:57:16.550-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:57:16.549-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:57:16.561-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:57:16.551-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 2, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-18T16:57:16.562-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:57:16.607-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.072 seconds
[2022-11-18T16:57:46.690-0300] {processor.py:153} INFO - Started process (PID=2511) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:57:46.693-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-18T16:57:46.693-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:57:46.693-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:57:46.700-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:57:46.698-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 2, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-18T16:57:46.701-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:57:46.766-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.078 seconds
[2022-11-18T16:58:20.034-0300] {processor.py:153} INFO - Started process (PID=2777) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:58:20.035-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-18T16:58:20.036-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:58:20.036-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:58:20.042-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:58:20.041-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 2, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-18T16:58:20.042-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:58:20.080-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.050 seconds
[2022-11-18T16:58:52.884-0300] {processor.py:153} INFO - Started process (PID=2980) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:58:52.890-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-18T16:58:52.891-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:58:52.891-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:58:52.894-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:58:52.893-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 2, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-18T16:58:52.895-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:58:52.918-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.039 seconds
[2022-11-18T16:59:23.402-0300] {processor.py:153} INFO - Started process (PID=3168) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:59:23.403-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-18T16:59:23.404-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:59:23.404-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:59:23.408-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:59:23.407-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-18T16:59:23.408-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:59:23.436-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.038 seconds
[2022-11-18T16:59:55.358-0300] {processor.py:153} INFO - Started process (PID=3359) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:59:55.363-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-18T16:59:55.364-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:59:55.364-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:59:55.370-0300] {logging_mixin.py:115} INFO - [2022-11-18T16:59:55.367-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-18T16:59:55.371-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T16:59:55.396-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.043 seconds
[2022-11-18T17:00:29.085-0300] {processor.py:153} INFO - Started process (PID=3522) to work on /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T17:00:29.087-0300] {processor.py:640} INFO - Processing file /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py for tasks to queue
[2022-11-18T17:00:29.088-0300] {logging_mixin.py:115} INFO - [2022-11-18T17:00:29.088-0300] {dagbag.py:508} INFO - Filling up the DagBag from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T17:00:29.092-0300] {logging_mixin.py:115} INFO - [2022-11-18T17:00:29.090-0300] {dagbag.py:321} ERROR - Failed to import: /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/juliana/Área de Trabalho/datapipeline/.env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py", line 4, in <module>
    from airflow.operators.alura import TwitterOperator
ModuleNotFoundError: No module named 'airflow.operators.alura'
[2022-11-18T17:00:29.092-0300] {processor.py:652} WARNING - No viable dags retrieved from /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py
[2022-11-18T17:00:29.119-0300] {processor.py:161} INFO - Processing /home/juliana/Área de Trabalho/datapipeline/airflow/dags/twitter_dag.py took 0.040 seconds
